apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
spec: {}
data:
  db-nonroot-password: <DB_NONROOT_PASSWORD>
  db-nonroot-user: <DB_NONROOT_USER>
  db-root-password: <DB_ROOT_PASSWORD>
  db-user: <DB_USER>
  encryption-key: <ENCRYPTION_KEY>
  n8n-runners-auth-token: <N8N_RUNNERS_AUTH_TOKEN>
type: Opaque
