apiVersion: v1
kind: Service
metadata:
  name: n8n
  annotations:
    metallb.io/loadBalancerIP: 192.168.29.135
spec:
  selector:
    app: n8n
  ports:
  - port: 5679
    targetPort: 5679
    protocol: TCP
    name: broker
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer
